name:         reply
version:      0.2.0-dev
description:  Utilities for recording and replaying API interactions
homepage:     https://github.com/matanlurey/reply.dart
authors:
              - Matan Lurey <matanl@lurey.org>
              - Brian Robles <brianrobles204@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: '^1.15.0'

dev_dependencies:
  test: '^1.17.10'
